version: '3.9'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./model:/app/model
    depends_on:
      - model

  model:
    build: ./model
    volumes:
      - ./model:/app
